# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_relacionvideotag_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=80)),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='relacionvideotag',
            name='video',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='idTag',
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(to='video.Tag'),
        ),
        migrations.DeleteModel(
            name='RelacionVideoTag',
        ),
        migrations.AddField(
            model_name='video',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.Subject'),
        ),
    ]
