# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20171220_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='timr',
            new_name='lenght',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='nick',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='video',
            name='tittle',
        ),
        migrations.AddField(
            model_name='subject',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.Video'),
        ),
    ]
